第３回講座
SaoriMichiguchi/Raise-Tech pull request #3
Opened 2023-07-15 10:42 UTC by SaoriMichiguchi

第３回講座課題

確認お願い致します。

2023-07-15 11:53 UTC, MasatoshiMizumoto requested changes
画像がpushされてないのでご対応お願いします！！

2023-07-15 11:53 UTC, MasatoshiMizumoto commented on lecture03.md
> +![](第３回課題２.png)
画像ってどうされてますか？？

2023-07-18 05:21 UTC, SaoriMichiguchi reviewed
このやり方で合ってますでしょうか？

2023-07-18 05:21 UTC, SaoriMichiguchi commented on lecture03.md
> +![](第３回課題２.png)
<img width="1315" alt="第３回課題２" src="https://github.com/SaoriMichiguchi/Raise-Tech/assets/138193025/b9733106-fd5d-48c7-9952-7a0d5db8278e">

2023-07-18 05:21 UTC, SaoriMichiguchi commented on lecture03.md
> +![](第３回課題１.png)
<img width="1414" alt="第３回課題１" src="https://github.com/SaoriMichiguchi/Raise-Tech/assets/138193025/b8d51d6c-d10f-4575-ad65-3712014af951">

2023-07-18 05:21 UTC, SaoriMichiguchi commented on lecture03.md
> +![](第３回課題３.png)
<img width="1332" alt="第３回課題３" src="https://github.com/SaoriMichiguchi/Raise-Tech/assets/138193025/cb0c1de6-15a3-4c8b-9f09-0463c65c5278">

2023-07-18 07:28 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-07-18 08:14 UTC, MasatoshiMizumoto approved these changes

2023-07-18 08:17 UTC, merged